default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: my_app_development
  username: postgres
  password: 
  host: localhost

test:
  <<: *default
  database: my_app_test
  username: postgres
  password: 
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
